#!/bin/bash

## file inputs
ANAT=`jq -r '.anat' config.json`

## CSD fits
LMAX2=`jq -r '.lmax2' config.json`
LMAX4=`jq -r '.lmax4' config.json`
LMAX6=`jq -r '.lmax6' config.json`
LMAX8=`jq -r '.lmax8' config.json`
LMAX10=`jq -r '.lmax10' config.json`
LMAX12=`jq -r '.lmax12' config.json`
LMAX14=`jq -r '.lmax14' config.json`

TFILE=$ANAT

if [ -f $LMAX2 ]; then
    echo "Transferring lmax2..."
    TFILE=$TFILE,$LMAX2
fi

if [ -f $LMAX4 ]; then
    echo "Transferring lmax4..."
    TFILE=$TFILE,$LMAX4
fi

if [ -f $LMAX6 ]; then
    echo "Transferring lmax6..."
    TFILE=$TFILE,$LMAX6
fi

if [ -f $LMAX8 ]; then
    echo "Transferring lmax8..."
    TFILE=$TFILE,$LMAX8
fi

if [ -f $LMAX10 ]; then
    echo "Transferring lmax10..."
    TFILE=$TFILE,$LMAX10
fi

if [ -f $LMAX12 ]; then
    echo "Transferring lmax12..."
    TFILE=$TFILE,$LMAX12
fi

if [ -f $LMAX14 ]; then
    echo "Transferring lmax14..."
    TFILE=$TFILE,$LMAX14
fi

NFIB=`jq -r '.num_fibers' config.json`

## use what exists to build file list

cat << EOF
universe = vanilla
arguments = $NFIB
executable = mrtrix3_tracking.sh

Requirements = HAS_SINGULARITY == TRUE

+ProjectName="Diffusion-predictor"
+SingularityImage = "/cvmfs/singularity.opensciencegrid.org/brainlife/mrtrix3:3.0_RC3"
+SingularityBindCVMFS = True

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT

# Send the job to Held state on failure.
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

# Periodically retry the jobs every 10 minutes, up to a maximum of 5 retries.
periodic_release =  (NumJobStarts < 5) && ((CurrentTime - EnteredCurrentStatus) > 600)

# remove job if it fails 5 times.
periodic_remove = (NumJobStarts == 5)

transfer_input_files = $TFILE
transfer_output_files = out

stream_output = True
output = stdout.log
error = stderr.log
log = condor.out

queue
EOF

